### ISSUE TITLE
Using CookieCutter?

### ISSUE THREAD

**Issue by pradyunsg** [return42/boilerplate#1]
This looks interesting... :)

Have you thought about making this repository compatible with https://pypi.org/project/cookiecutter/?

**Comment by return42** [comment]
Hi @pradyunsg, good point. cookiecutter is new to me, but makes a good first impression to me. If I have time I will pick up your suggestion. Thanks!

**Comment by pradyunsg** [comment]
Closing since doesn't look like anyone's gonna be doing this. :)
